# Generated by Django 5.1.3 on 2024-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_cover_alter_recipe_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time',
            new_name='servings',
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(default=2, upload_to='recipes/covers/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
